apiVersion: batch/v1
kind: Job
metadata:
  name: go-hello-build
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.23.2
        args:
          - "--context=git://github.com/troycarpenter/go-test.git"
          - "--dockerfile=Dockerfile"
          - "--destination=harbor.carpenter.cx/library/go-hello:${TAG}"
          - "--cleanup"
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      volumes:
      - name: docker-config
        secret:
          secretName: harbor-regcred
